version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:

  build:

    docker:
      - image: circleci/openjdk:9

    steps:
      - checkout

      - restore_cache:
          name: Restore cache
          key: maven-cache-v1-{{ checksum "pom.xml" }}

      - run:
          name: Install dependecies
          command: mvn install

      - save_cache:
          name: Save cache
          key: maven-cache-v1-{{ checksum "pom.xml" }}
          paths:
            - ../

      - run:
          name: Run tests
          command: mvn test
      
      - codecov/upload:
          conf: codecov.yml
          file: target/site/jacoco/jacoco.xml